Imports System.Text
Imports PSS.Data.Buisness.Generic

Namespace BLL

	Public Class TNSIMMiscDataProvider

#Region "DECLARATIONS"

		Private _cust_id As Integer = 0
		Private _loc_id As Integer = 0
		Private _prod_id As Integer = 0
		Private _group_id As Integer = 0
		Private _user_id As Integer = 0
		Private _objDataProc As DBQuery.DataProc

#End Region
#Region "CONSTRUCTORS"

		Public Sub New(ByVal user_id As Integer)
			Dim _tn As New Buisness.TN()
			_cust_id = _tn.CUSTOMERID
			_loc_id = _tn.LOCID
			_prod_id = _tn.PRODID
			_group_id = _tn.GROUPID
			_tn = Nothing
			_user_id = user_id
			_objDataProc = New DBQuery.DataProc(ConfigFile.GetConnectionInfo)
		End Sub

#End Region
#Region "DATA PROVIDER METHODS"

		Public Function GetAllOrdersBySku(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(co.co_id) AS orders ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetAllOrdersCountBySku(ByVal start_date As Date, ByVal end_date As Date) As Integer
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("COUNT(co.co_id) AS count ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			_cnt = _dt.Rows(0)(0)
			_dt = Nothing
			Return _cnt
		End Function
		Public Function GetOpenOrdersBySku(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(co.co_id) AS orders ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("wo.WO_Closed = 0 ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetOpenOrdersCount(ByVal start_date As Date, ByVal end_date As Date) As Integer
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("COUNT(co.co_id) AS count ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("wo.WO_Closed = 0 ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			_cnt = _dt.Rows(0)(0)
			_dt = Nothing
			Return _cnt
		End Function
		Public Function GetFilledOrdersBySku(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(co.co_id) AS orders ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("soh.shipdate IS NOT NULL ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetFilledOrdersCount(ByVal start_date As Date, ByVal end_date As Date) As Integer
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("COUNT(co.co_id) AS count ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.OrderStatusID = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("wo.WO_Closed = 1 ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			_cnt = _dt.Rows(0)(0)
			_dt = Nothing
			Return _cnt
		End Function
		Public Function GetKittedItemsBySku() As DataTable
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(whi.wi_id) AS Items ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id > 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetKittedItemCount() As Integer
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("COUNT(whi.wi_id) AS Items ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id > 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			_cnt = _dt.Rows(0)(0)
			_dt = Nothing
			Return _cnt
		End Function
		Public Function GetAllInventoryBySku()
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(whi.wi_id) AS Items ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN warehouse.warehouse_receipt whr ON whi.wr_id = whr.wr_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("whr.cust_id = ")
			_sb.Append(_cust_id & " ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetNonKittedBySku()
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("COUNT(whi.wi_id) AS Items ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN warehouse.warehouse_receipt whr ON whi.wr_id = whr.wr_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id = 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("whr.cust_id = ")
			_sb.Append(_cust_id & " ")
			_sb.Append("GROUP BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetNonKittedCount() As Integer
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("COUNT(whi.wi_id) AS Items ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN warehouse.warehouse_receipt whr ON whi.wr_id = whr.wr_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id = 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("whr.cust_id = ")
			_sb.Append(_cust_id & " ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			_cnt = _dt.Rows(0)(0)
			_dt = Nothing
			Return _cnt
		End Function
		Public Function GetAllOrders(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("DATE_FORMAT(co.date_rec,'%m-%d-%Y') AS date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" ")
			_sb.Append("ORDER BY ")
			_sb.Append("co.date_rec ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetOpenOrders(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("co.date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("soh.ShipDate IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function
		Public Function GetFilledOrders(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("co.date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 0 ")
			_sb.Append(" AND ")
			_sb.Append("soh.ShipDate BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" ")
			_sb.Append("ORDER BY ")
			_sb.Append("co.date_rec ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt

		End Function
		Public Function GetRejectedOrders(ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("DATE_FORMAT(co.date_rec,'%m-%d-%Y') AS date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("soh.ReasonOrderInvalid, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("soh.invalidorder = 1 ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" ")
            '_sb.Append("GROUP BY ")
            '_sb.Append("sku.sku_part_nr ")
			_sb.Append("ORDER BY ")
			_sb.Append("co.date_rec ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt

		End Function

#Region "FOR SKU QUERIES"

		Public Function GetKittedForSku(ByVal Sku As String) As DataTable
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("d.device_sn, ")
			_sb.Append("d.device_daterec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("sku.sku ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id > 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("sku.sku_part_nr = '" & Sku & "'")
			_sb.Append("ORDER BY ")
			_sb.Append("d.device_sn ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function

		Public Function GetNonKittedForSku(ByVal Sku As String) As DataTable
			Dim _cnt As Integer = 0
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			_sb.Append("SELECT ")
			_sb.Append("d.device_sn, ")
			_sb.Append("d.device_daterec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("sku.sku ")
			_sb.Append("FROM production.tcust_sku sku ")
			_sb.Append("INNER JOIN warehouse.warehouse_items whi ON sku.sku_id = whi.sku_id ")
			_sb.Append("INNER JOIN production.tdevice d ON whi.device_id = d.device_id ")
			_sb.Append("WHERE ")
			_sb.Append("whi.insert_decode_id = 0 ")
			_sb.Append(" AND ")
			_sb.Append("d.device_dateship IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("sku.sku_part_nr = '" & Sku & "'")
			_sb.Append("ORDER BY ")
			_sb.Append("d.device_sn ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function

		Public Function GetAllOrdersForSku(ByVal sku As String, ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("DATE_FORMAT(co.date_rec,'%m-%d-%Y') AS date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("d.device_sn, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("LEFT JOIN production.tdevice d on wo.wo_id = d.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("sku.sku_part_nr = '" & sku & "' ")
			_sb.Append("ORDER BY ")
			_sb.Append("co.date_rec ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function

		Public Function GetOpenOrdersForSku(ByVal sku As String, ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("DATE_FORMAT(co.date_rec,'%m-%d-%Y') AS date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("d.device_sn, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("LEFT JOIN production.tdevice d on wo.wo_id = d.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("soh.ShipDate IS NULL ")
			_sb.Append(" AND ")
			_sb.Append("sku.sku_part_nr = '" & sku & "' ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function

		Public Function GetFilledOrdersForSku(ByVal sku As String, ByVal start_date As Date, ByVal end_date As Date) As DataTable
			Dim _dt As New DataTable()
			Dim _sb As New StringBuilder()
			Dim _start As New Date()
			_start = GetFirstSecondOfDate(start_date)
			Dim _end As New Date()
			_end = GetLastSecondOfDate(end_date)
			_sb.Append("SELECT ")
			_sb.Append("soh.ponumber, ")
			_sb.Append("DATE_FORMAT(co.date_rec,'%m-%d-%Y') AS date_rec, ")
			_sb.Append("sku.sku_part_nr, ")
			_sb.Append("d.device_sn, ")
			_sb.Append("soh.CustomerFirstName, ")
			_sb.Append("soh.CustomerAddress1, ")
			_sb.Append("soh.CustomerAddress2, ")
			_sb.Append("soh.CustomerCity, ")
			_sb.Append("soh.CustomerState, ")
			_sb.Append("soh.CustomerCountry, ")
			_sb.Append("DATE_FORMAT(soh.ShipDate,'%m-%d-%Y') AS ShipDate, ")
			_sb.Append("'" & start_date.ToShortDateString() & "' AS StartDate, ")
			_sb.Append("'" & end_date.ToShortDateString() & "' AS EndDate ")
			_sb.Append("FROM edi.tcust_order co ")
			_sb.Append("INNER JOIN saleorders.soheader soh ON co.wo_id = soh.WorkOrderID ")
			_sb.Append("INNER JOIN saleorders.sodetails sod ON soh.soheaderid = sod.soheaderid ")
			_sb.Append("INNER JOIN production.tcust_sku sku ON sod.sku = sku.sku ")
			_sb.Append("INNER JOIN production.tworkorder wo ON co.wo_id = wo.wo_id ")
			_sb.Append("LEFT JOIN production.tdevice d on wo.wo_id = d.wo_id ")
			_sb.Append("WHERE ")
			_sb.Append("soh.cust_id = " & _cust_id.ToString() & " ")
			_sb.Append(" AND ")
			_sb.Append("co.date_rec BETWEEN ")
			_sb.Append(ConvertToMySQLDateOrNullString(_start))
			_sb.Append(" AND ")
			_sb.Append(ConvertToMySQLDateOrNullString(_end))
			_sb.Append(" AND ")
			_sb.Append("soh.ShipDate IS NOT NULL ")
			_sb.Append(" AND ")
			_sb.Append("sku.sku_part_nr = '" & sku & "' ")
			_sb.Append("ORDER BY ")
			_sb.Append("sku.sku_part_nr ")
			_sb.Append("; ")
			_dt = _objDataProc.GetDataTable(_sb.ToString())
			Return _dt
		End Function




#End Region


#End Region

	End Class

End Namespace
